-- Beauty Mondial Academy · schema production
create extension if not exists "uuid-ossp";
create type public.reservation_status as enum ('pending','confirmed','cancelled','completed');
create table public.rooms (id uuid primary key default uuid_generate_v4(),name text not null unique,description text,capacity int not null check(capacity>0),daily_price numeric(10,2),weekly_price numeric(10,2),monthly_price numeric(10,2),image text,created_at timestamptz not null default now());
create table public.pricing (id uuid primary key default uuid_generate_v4(),room_id uuid references public.rooms(id) on delete cascade,daily numeric(10,2),weekly numeric(10,2),monthly numeric(10,2),long_term text,updated_at timestamptz not null default now(),unique(room_id));
create table public.reservations (id uuid primary key default uuid_generate_v4(),first_name text not null,last_name text not null,email text not null,phone text not null,whatsapp text,room_id uuid not null references public.rooms(id),reservation_date date not null check(reservation_date>=current_date),status public.reservation_status not null default 'pending',notes text,created_at timestamptz not null default now(),unique(room_id,reservation_date));
create table public.blocked_dates (id uuid primary key default uuid_generate_v4(),room_id uuid references public.rooms(id) on delete cascade,reservation_date date not null,created_at timestamptz not null default now(),unique(room_id,reservation_date));
create table public.gallery (id uuid primary key default uuid_generate_v4(),image text not null,title text,created_at timestamptz not null default now());
create table public.equipments (id uuid primary key default uuid_generate_v4(),name text not null,description text,image text,created_at timestamptz not null default now());
create index reservations_date_idx on public.reservations(reservation_date); create index reservations_status_idx on public.reservations(status); create index blocked_dates_date_idx on public.blocked_dates(reservation_date);
create or replace view public.availability as select r.id room_id,d.day reservation_date,not exists(select 1 from reservations x where x.room_id=r.id and x.reservation_date=d.day and x.status in ('pending','confirmed')) and not exists(select 1 from blocked_dates b where b.room_id=r.id and b.reservation_date=d.day) available from rooms r cross join lateral generate_series(current_date,current_date+365,interval '1 day') d(day);
alter table public.rooms enable row level security; alter table public.pricing enable row level security; alter table public.reservations enable row level security; alter table public.blocked_dates enable row level security; alter table public.gallery enable row level security; alter table public.equipments enable row level security;
create policy "public read rooms" on public.rooms for select using(true); create policy "public read pricing" on public.pricing for select using(true); create policy "public read gallery" on public.gallery for select using(true); create policy "public read equipment" on public.equipments for select using(true); create policy "public read availability" on public.blocked_dates for select using(true);
create policy "public can request" on public.reservations for insert with check(status='pending');
-- Admin access: add the role in auth.users raw_app_meta_data: {"role":"admin"}
create policy "admins manage rooms" on public.rooms for all using((auth.jwt()->'app_metadata'->>'role')='admin'); create policy "admins manage pricing" on public.pricing for all using((auth.jwt()->'app_metadata'->>'role')='admin'); create policy "admins manage reservations" on public.reservations for all using((auth.jwt()->'app_metadata'->>'role')='admin'); create policy "admins manage blocked" on public.blocked_dates for all using((auth.jwt()->'app_metadata'->>'role')='admin'); create policy "admins manage gallery" on public.gallery for all using((auth.jwt()->'app_metadata'->>'role')='admin'); create policy "admins manage equipment" on public.equipments for all using((auth.jwt()->'app_metadata'->>'role')='admin');
insert into public.rooms(name,description,capacity) values ('Petite Salle','Salle intime entièrement équipée',2),('Grande Salle','Salle spacieuse et modulable',3) on conflict(name) do nothing;
