'use client';
import Image from 'next/image';
import {motion, AnimatePresence} from 'framer-motion';
import {ArrowUpRight, CalendarDays, Check, ChevronRight, Coffee, Facebook, Instagram, LampDesk, MessageCircle, Music2, Phone, Pin, MapPin, Sparkles, Wifi, X} from 'lucide-react';
import {useEffect,useState} from 'react';
import {BookingForm} from '@/components/booking-form';
import {supabase} from '@/lib/supabase';
const photos=['WhatsApp Image 2026-07-27 at 18.07.56.jpeg','WhatsApp Image 2026-07-27 at 18.12.26 (1).jpeg','WhatsApp Image 2026-07-27 at 18.12.26 (2).jpeg','WhatsApp Image 2026-07-27 at 18.12.26.jpeg','WhatsApp Image 2026-07-27 at 18.12.27 (1).jpeg','WhatsApp Image 2026-07-27 at 18.12.27 (2).jpeg','WhatsApp Image 2026-07-27 at 18.12.27 (3).jpeg','WhatsApp Image 2026-07-27 at 18.12.27 (4).jpeg','WhatsApp Image 2026-07-27 at 18.12.27 (5).jpeg','WhatsApp Image 2026-07-27 at 18.12.27.jpeg'];
const equipment=['Lampe d’éclairage professionnelle','Vapozone visage','Hydrafacial','Radiofréquence','Lipoactivation','Madero Therapy','Mobilier esthétique','Fauteuils professionnels','Équipement coiffure','Tables de massage','Machine à café & thé','Cuisine équipée','Bloc sanitaire','TV & rétroprojecteur','Baffles Bluetooth','Connexion WiFi','Climatisation','Salle d’attente'];
const reveal={initial:{opacity:0,y:22},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.7}};
type PriceRoom={name:string;daily_price:number|null;weekly_price:number|null;monthly_price:number|null};
const formatTnd=(price:number|null|undefined)=>price==null?'Sur demande':new Intl.NumberFormat('fr-TN',{maximumFractionDigits:3}).format(price)+' TND';
export function Landing(){const [lightbox,setLightbox]=useState<string|null>(null);const [roomPrices,setRoomPrices]=useState<PriceRoom[]>([]);useEffect(()=>{const client=supabase();Promise.all([client.from('rooms').select('id,name'),client.from('pricing').select('room_id,daily,weekly,monthly')]).then(([{data:roomsData},{data:pricingData}])=>setRoomPrices((roomsData??[]).map(room=>{const price=pricingData?.find(item=>item.room_id===room.id);return {name:room.name,daily_price:price?.daily??null,weekly_price:price?.weekly??null,monthly_price:price?.monthly??null}})))},[]);return <main className="overflow-hidden">
<nav className="fixed left-3 right-3 top-3 z-40 flex h-20 items-center justify-between rounded-full border border-white/10 bg-[#111]/75 px-5 shadow-[0_12px_40px_rgba(0,0,0,.32)] backdrop-blur-2xl transition-all duration-500 hover:border-gold/40 md:left-6 md:right-6 md:px-10"><a href="#top" aria-label="Beauty Mondial Academy"><Image src="/gallery/3-scaled.png" alt="Beauty Mondial Academy" width={96} height={96} className="h-28 w-28 object-contain drop-shadow-[0_0_18px_rgba(212,175,55,.18)] md:h-36 md:w-36"/></a><div className="hidden gap-7 text-[10px] font-bold tracking-[.15em] text-mist lg:flex"><a href="#concept">CONCEPT</a><a href="#salles">LES SALLES</a><a href="#galerie">GALERIE</a><a href="#tarifs">TARIFS</a></div><a href="#reservation" className="btn-gold !px-4 !py-2.5 !text-[10px]">Réserver <ArrowUpRight size={14}/></a></nav>
<section id="top" className="relative min-h-[800px] px-6 pt-32 md:px-12"><Image priority fill src={'/gallery/'+photos[0]} alt="Espace Beauty Mondial Academy" className="object-cover opacity-45"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#111_10%,rgba(17,17,17,.48)_65%,#111),linear-gradient(0deg,#111,transparent_45%)]"/><div className="relative mx-auto flex min-h-[650px] max-w-7xl flex-col justify-center"><motion.p {...reveal} className="eyebrow mb-7 flex items-center gap-3"><span className="h-px w-8 bg-gold"/> L&apos;adresse des professionnels de la beauté</motion.p><motion.h1 {...reveal} transition={{duration:.8,delay:.1}} className="max-w-4xl text-5xl font-light leading-[.93] tracking-[-.055em] sm:text-7xl lg:text-8xl">Coworking<br/><em className="font-serif text-gold">Beauté.</em></motion.h1><motion.p {...reveal} transition={{delay:.2}} className="mt-8 max-w-lg text-base leading-7 text-mist">Travaillez dans un espace professionnel entièrement équipé, sans louer un local à l’année.</motion.p><motion.div {...reveal} transition={{delay:.3}} className="mt-10 flex flex-wrap gap-3"><a className="btn-gold" href="#reservation">Réserver une salle <CalendarDays size={16}/></a><a className="btn-ghost" href="#tarifs">Demander les tarifs</a></motion.div></div><div className="absolute bottom-8 right-6 hidden items-center gap-3 text-[10px] tracking-[.2em] text-mist md:flex">DÉCOUVRIR <span className="h-8 w-px bg-gold"/></div></section>
<section id="concept" className="section grid gap-12 md:grid-cols-[.75fr_1.25fr] md:items-end"><motion.div {...reveal}><p className="eyebrow">01 — L&apos;expérience BMA</p><h2 className="mt-5 text-4xl font-light tracking-tight md:text-5xl">Le lieu qui donne<br/>de l&apos;ampleur à votre <em className="text-gold">talent.</em></h2></motion.div><motion.p {...reveal} transition={{delay:.15}} className="max-w-xl text-lg font-light leading-8 text-mist">Beauty Mondial Academy propose désormais un espace de coworking destiné aux professionnelles de la beauté souhaitant recevoir leurs clientes dans un cadre premium sans investissement important.</motion.p></section>
<section className="px-6 pb-28 md:px-12"><div className="mx-auto grid max-w-7xl gap-px overflow-hidden rounded-3xl border border-gold/20 bg-gold/20 md:grid-cols-3">{[['01','Salles entièrement équipées','Profitez d’un espace professionnel prêt à travailler.'],['02','Sans engagement','Ne payez que lorsque vous utilisez la salle.'],['03','Cadre Premium','Recevez vos clientes dans un environnement luxueux.']].map(([n,t,d])=><motion.article {...reveal} key={n} className="group bg-ink p-8 transition hover:bg-[#181715] md:p-10"><span className="text-xs tracking-[.2em] text-gold">{n}</span><h3 className="mt-16 text-2xl font-light">{t}</h3><p className="mt-4 max-w-xs leading-7 text-mist">{d}</p><ArrowUpRight className="mt-10 text-gold transition group-hover:translate-x-1 group-hover:-translate-y-1"/></motion.article>)}</div></section>
<section className="relative border-y border-white/10 py-28"><div className="absolute inset-0 noise opacity-20"/><div className="section relative py-0 text-center"><p className="eyebrow">Une nouvelle liberté</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-light tracking-tight md:text-6xl">Développez votre activité<br/>à <em className="text-gold">moindre coût.</em></h2><p className="mt-7 text-mist">Une solution idéale pour les talents indépendants.</p><div className="mx-auto mt-12 flex max-w-4xl flex-wrap justify-center gap-3">{['Esthéticiennes','Facialistes','Masseurs','Coiffeuses','Lash Artists','Nail Artists','Maquilleuses','Praticiennes bien-être'].map(x=><span key={x} className="rounded-full border border-white/15 px-5 py-3 text-xs tracking-wide text-cream">{x}</span>)}</div></div></section>
<section id="equipements" className="section"><motion.div {...reveal} className="mb-12 flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">02 — Tout est déjà là</p><h2 className="mt-4 text-4xl font-light md:text-6xl">Vos outils. Votre <em className="text-gold">vision.</em></h2></div><p className="max-w-sm text-sm leading-6 text-mist">Un environnement conçu dans les moindres détails pour vous laisser vous concentrer sur l’essentiel.</p></motion.div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{equipment.map((x,i)=><motion.div {...reveal} transition={{delay:(i%3)*.05}} key={x} className="group glass flex min-h-32 items-end justify-between rounded-2xl p-5 hover:border-gold/60"><div><span className="text-[10px] tracking-[.16em] text-gold">{String(i+1).padStart(2,'0')}</span><h3 className="mt-3 text-base font-normal">{x}</h3></div><Image src={i===5?"/gallery/1-pillar-madero-therapy-guide.webp":"/gallery/"+photos[i%photos.length]} width={110} height={110} alt={x} className="h-20 w-24 rounded-xl object-cover opacity-65 transition duration-500 group-hover:scale-105 group-hover:opacity-100"/></motion.div>)}</div></section>
<section id="salles" className="section pt-0"><p className="eyebrow mb-8">03 — Choisir son rythme</p><div className="grid gap-5 lg:grid-cols-2">{[{name:'Petite Salle',image:photos[6],desc:'L’intimité parfaite pour les rendez-vous personnalisés.',list:['2 tables de massage','Éclairage professionnel','Hydrafacial & Vapozone','Radio fréquence','TV & Mobilier']},{name:'Grande Salle',image:photos[3],desc:'L’espace généreux pour déployer vos prestations.',list:['3 tables de massage','Équipements complets','Rétroprojecteur & TV','Baffles Bluetooth','Cuisine à proximité']}].map(r=><motion.article {...reveal} key={r.name} className="group relative min-h-[520px] overflow-hidden rounded-3xl border border-white/10"><Image fill src={'/gallery/'+r.image} alt={r.name} className="object-cover opacity-65 transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#111] via-[#111]/40 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 md:p-10"><p className="eyebrow">{r.name==='Petite Salle'?'Intime & complète':'Spacieuse & modulable'}</p><h3 className="mt-3 text-4xl font-light">{r.name}</h3><p className="mt-3 text-mist">{r.desc}</p><ul className="mt-7 grid grid-cols-2 gap-y-3 text-sm text-cream">{r.list.map(l=><li key={l} className="flex items-center gap-2"><Check size={14} className="text-gold"/>{l}</li>)}</ul></div></motion.article>)}</div></section>
<section id="galerie" className="pb-28"><div className="section py-0"><div className="mb-10 flex justify-between"><div><p className="eyebrow">04 — L&apos;atmosphère</p><h2 className="mt-4 text-4xl font-light">La galerie <em className="text-gold">BMA.</em></h2></div><span className="hidden self-end text-xs text-mist md:block">Cliquez pour agrandir</span></div></div><div className="grid grid-cols-2 gap-2 px-2 md:grid-cols-4">{photos.map((p,i)=><button key={p} onClick={()=>setLightbox(p)} className={'group relative overflow-hidden '+(i===0||i===5?'col-span-2 aspect-[2/1]':'aspect-square')}><Image fill src={'/gallery/'+p} alt={'Galerie Beauty Mondial Academy '+(i+1)} className="object-cover transition duration-500 group-hover:scale-105 group-hover:opacity-75"/></button>)}</div></section>
<section id="tarifs" className="section border-y border-white/10"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">05 — Transparence</p><h2 className="mt-5 text-4xl font-light md:text-5xl">Des tarifs à la mesure de votre <em className="text-gold">ambition.</em></h2><p className="mt-5 max-w-sm leading-7 text-mist">Choisissez votre horizon. Pour les projets longue durée, nous créons une proposition sur mesure.</p></div><div className="overflow-hidden rounded-3xl border border-gold/25"><div className="grid grid-cols-4 border-b border-white/10 bg-white/5 p-5 text-[10px] font-bold tracking-[.14em] text-mist"><span>ESPACE</span><span>JOURNÉE</span><span>SEMAINE</span><span>MOIS</span></div>{['Petite Salle','Grande Salle'].map(name=>{const room=roomPrices.find(item=>item.name===name);return <div className="grid grid-cols-4 border-b border-white/10 p-5 text-sm" key={name}><span className="text-cream">{name}</span><span className="text-gold">{formatTnd(room?.daily_price)}</span><span className="text-gold">{formatTnd(room?.weekly_price)}</span><span className="text-gold">{formatTnd(room?.monthly_price)}</span></div>})}<div className="flex flex-wrap items-center justify-between gap-4 p-5"><span className="text-sm text-mist">Longue durée — tarif personnalisé</span><a href="#reservation" className="btn-gold !py-2.5 !text-[10px]">Demander un devis <ChevronRight size={14}/></a></div></div></div></section>
<section id="reservation" className="section"><div className="mx-auto max-w-4xl rounded-3xl border border-gold/25 bg-gradient-to-br from-[#201d14] to-[#161616] p-6 md:p-12"><p className="eyebrow">06 — Votre créneau</p><h2 className="mt-4 text-4xl font-light">Réserver une <em className="text-gold">salle.</em></h2><p className="mt-4 text-mist">Les journées indisponibles ne peuvent pas être sélectionnées.</p><BookingForm/></div></section>
<section className="section pt-0"><div className="relative overflow-hidden rounded-3xl border border-white/10 bg-[#171717] p-8 md:p-14"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_top_right,rgba(212,175,55,.14),transparent_65%)]"/><div className="relative grid gap-10 md:grid-cols-2"><div><p className="eyebrow">Nous trouver</p><h2 className="mt-4 text-4xl font-light">Échangeons sur votre <em className="text-gold">projet.</em></h2><div className="mt-8 space-y-4 text-mist"><a href="https://wa.me/330695697778" className="flex items-center gap-3 hover:text-gold"><MessageCircle size={17} className="text-gold"/> WhatsApp · +33 06 95 69 77 78</a><a href="tel:+21658168903" className="flex items-center gap-3 hover:text-gold"><Phone size={17} className="text-gold"/> Téléphone Tunisie · +216 58 168 903</a><a href="https://www.google.com/maps/search/?api=1&query=Kantaoui%2C+Sousse%2C+Tunisie" target="_blank" rel="noreferrer" className="flex items-center gap-3 hover:text-gold"><MapPin size={17} className="text-gold"/> Kantaoui, Sousse · Tunisie</a><div className="flex items-center gap-3 pt-2"><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram" className="rounded-full border border-white/15 p-2 transition hover:border-gold hover:text-gold"><Instagram size={17}/></a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook" className="rounded-full border border-white/15 p-2 transition hover:border-gold hover:text-gold"><Facebook size={17}/></a><a href="https://www.pinterest.com/" target="_blank" rel="noreferrer" aria-label="Pinterest" className="rounded-full border border-white/15 p-2 transition hover:border-gold hover:text-gold"><Pin size={17}/></a><a href="https://www.tiktok.com/" target="_blank" rel="noreferrer" aria-label="TikTok" className="rounded-full border border-white/15 p-2 transition hover:border-gold hover:text-gold"><Music2 size={17}/></a></div></div></div><div className="relative aspect-square w-full overflow-hidden rounded-2xl border border-gold/20"><Image fill src="/gallery/design final.png" alt="Beauty Mondial Academy — localisation" className="object-contain object-center"/><a href="https://wa.me/330695697778" aria-label="Écrire sur WhatsApp" className="absolute bottom-4 right-4 flex h-12 w-12 items-center justify-center rounded-full bg-gold text-ink shadow-xl transition hover:scale-110"><MessageCircle size={22}/></a></div></div></div></section>
<a href="https://wa.me/330695697778" aria-label="Contacter Beauty Mondial Academy sur WhatsApp" className="fixed bottom-5 right-5 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-gold text-ink shadow-2xl transition hover:scale-110"><MessageCircle size={25}/></a><footer className="border-t border-white/10 px-6 py-9 md:px-12"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5"><Image src="/gallery/3-scaled.png" alt="Beauty Mondial Academy" width={70} height={70} className="h-24 w-24 object-contain md:h-28 md:w-28"/><span className="text-xs text-mist">© {new Date().getFullYear()} · Mentions légales · Politique de confidentialité</span></div></footer>
<AnimatePresence>{lightbox&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setLightbox(null)} className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 p-5"><button className="absolute right-6 top-6 text-white"><X/></button><Image src={'/gallery/'+lightbox} alt="Agrandissement galerie" width={1400} height={1000} className="max-h-[88vh] w-auto rounded-xl object-contain"/></motion.div>}</AnimatePresence>
</main>}











